# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ea92951372f727754b5365d0f65ca82e5f28f6b4d3ac9da3af87fa6e728304216a61cae0210a5106eadda0f73dd51e31d687a20ec281a1a9a681cdeb35bae56

test:
  secret_key_base: 597b07663e963f349db8c1e1cce8c1fb8d3349387e0f7dc8eebe921142c94c7ed81a732aa55aacd63bdf57d0a56b2be5c91779bfae1a8dabb37fa1f00b8ee69d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
